/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "../../src/plugins/strapi-plugin-ckeditor/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import redirects from "strapi-plugin-redirects/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import translate from "strapi-plugin-translate/strapi-admin";
import vercelDeploy from "strapi-plugin-vercel-deploy/strapi-admin";
import allCarsList from "../../src/plugins/all-cars-list/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    "strapi-cloud": strapiCloud,
    graphql: graphql,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "import-export-entries": importExportEntries,
    meilisearch: meilisearch,
    redirects: redirects,
    "rest-cache": restCache,
    translate: translate,
    "vercel-deploy": vercelDeploy,
    "all-cars-list": allCarsList,
  },
});
